refactor class MavenWrapperDownloader
takari/maven-wrapper pull request #154
Opened 2019-11-06 09:04 UTC by robatipoor

2019-11-06 09:14 UTC, fbricon requested changes

2019-11-06 09:14 UTC, fbricon commented on .mvn/wrapper/MavenWrapperDownloader.java
> +        if (args.length != 1) {
args.length < 1

2019-11-06 09:14 UTC, fbricon commented on .mvn/wrapper/MavenWrapperDownloader.java
> +            throw new IllegalArgumentException();
Add message to provide feedback on the failure

2019-11-06 15:04 UTC, robatipoor commented on .mvn/wrapper/MavenWrapperDownloader.java
> +        if (args.length != 1) {
ok done

2020-02-19 04:58 UTC, mosabua commented
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this PR. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.

2020-02-19 04:58 UTC, closed without merging