add basic auth support
takari/maven-wrapper pull request #96
Opened 2018-11-30 19:29 UTC by reinsch82

basically taken the code from [gradle wrapper](https://github.com/gradle/gradle/blob/master/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java) 

This would be helpful in corporate environments with inhouse maven server with authentication enabled
(I happen to work in a company like that)
I've done this in my spare time which means no corporate copyrights are attached.

2018-12-05 15:04 UTC, arbue approved these changes

2018-12-18 05:24 UTC, mosabua commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +       Logger.info("WARNING Using HTTP Basic Authentication over an insecure connection to download the Gradle distribution. Please consider using HTTPS.");
Maven distribution

2018-12-18 05:26 UTC, mosabua commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +    String username = System.getProperty("maven.wrapperUser");
Can you change this to use environment variables MVNW_USER and MVNW_PASSWORD to be consistent with the already used MVNW_VERBOSE and add documentation in the readme file into this PR?

I am hoping to release a new version of the wrapper soon..

2018-12-18 05:26 UTC, mosabua commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +import java.io.*;
please dont collapse the imports

2018-12-18 05:38 UTC, mosabua commented
I think this is not needed if https://github.com/takari/maven-wrapper/pull/86/files is fixed and merged. Right? As it stands this is kinda incomplete on its own.

2018-12-18 19:59 UTC, reinsch82 commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +       Logger.info("WARNING Using HTTP Basic Authentication over an insecure connection to download the Gradle distribution. Please consider using HTTPS.");
fixed

2018-12-18 20:00 UTC, reinsch82 commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +    String username = System.getProperty("maven.wrapperUser");
added

2018-12-18 20:00 UTC, reinsch82 commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +import java.io.*;
fixed

2018-12-18 20:12 UTC, reinsch82 commented
To my understanding these 2 PRs complete each other.
This one gets the Maven distribution with Basic auth.
The other one gets the maven wrapper jar with Basic auth.
We could use both I think.
Do I miss something in #86 ?
This on it's own does make sense. I currently can't see how just getting the wrapper would make sense on it's own. Where would I get the distribution from?

2018-12-18 20:20 UTC, sepe81 requested changes

2018-12-18 20:20 UTC, sepe81 commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +              throw new RuntimeException("Downloading Maven   distributions with HTTP Basic Authentication is not supported on your JVM.", java5OrEarlier);
Two duplicate spaces after `Downloading Maven` could be removed

2018-12-18 20:20 UTC, sepe81 commented on src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
> +       Logger.info("WARNING Using HTTP Basic Authentication over an insecure connection to download the Maven distribution. Please consider using HTTPS.");
It looks a bit confusing to put a WARNING into info logging. Why not use warn logging?

2018-12-19 19:25 UTC, sepe81 approved these changes

2018-12-19 20:04 UTC, sepe81 commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.0/apache-maven-3.6.0-bin.zip
Possibly this PR branch needs to be rebased with master b/c some changes are already present there.

see https://github.com/takari/maven-wrapper/commit/b93c46869a626d95af1908713580d88fc349937c

2019-02-18 18:27 UTC, merged